[#9] Dispatch stored events inside a repository
pheature-flags/toggle-crud pull request #11
Opened 2021-10-03 17:03 UTC by xserrat

Closes #9

2021-10-03 18:24 UTC, pcs289 approved these changes
🚀 🔥

2021-10-03 22:30 UTC, kpicaza requested changes
Good work!!! I will dispatch the events on the remove method.

2021-10-03 22:30 UTC, kpicaza commented on src/Repository/EventDispatcherAwareFeatureRepository.php
> +        $this->featureRepository->remove($featureId);
The remove method should dispatch events too

```suggestion
        $this->featureRepository->remove($featureId);
        
        $this->dispatchEvents($feature->release());
```

2021-10-05 19:48 UTC, xserrat commented on src/Repository/EventDispatcherAwareFeatureRepository.php
> +        $this->featureRepository->remove($featureId);
If we need it we should update the `remove` contract because now it expects a `FeatureId` instead of a `Feature` entity. What do you think?

2021-10-05 20:15 UTC, kpicaza commented on src/Repository/EventDispatcherAwareFeatureRepository.php
> +        $this->featureRepository->remove($featureId);
Uhmmm, nice point, we have to check what changes but you are right, we need the feature object here

2021-10-06 18:03 UTC, xserrat commented on src/Repository/EventDispatcherAwareFeatureRepository.php
> +        $this->featureRepository->remove($featureId);
I'm going to check it and I might refactor this part!

2021-10-07 17:13 UTC, xserrat commented on src/Repository/EventDispatcherAwareFeatureRepository.php
> +        $this->featureRepository->remove($featureId);
done!

2021-10-07 17:18 UTC, kpicaza approved these changes
:rocket:

2021-10-08 17:00 UTC, merged