[#13] feat: :sparkles: Adding Php 8.1 Support
pheature-flags/toggle-crud pull request #14
Opened 2021-10-20 05:00 UTC by AndreyPootMay

Adding php ^8.1 support #hacktoberfest

Issue #13

---

The CI have an enviroment in 8.1?

2021-10-20 18:47 UTC, kpicaza requested changes

2021-10-20 18:47 UTC, kpicaza commented on composer.json
> +        "php": "^7.4|^8.1",
Hi @AndreyPootMay :wave: Thank you very much for the contribution :tada::tada::tada: 

Check the following suggestion, only allowing PHP ^7.4|^8.1 will block installing with PHP 8.0
```suggestion
        "php": "^7.4|^8.0|^8.1",
```

2021-10-21 01:43 UTC, AndreyPootMay commented
Check :D, greetings from México

2021-10-21 15:26 UTC, kpicaza commented on composer.json.save
> +{
This file is not need ;-D

2021-10-21 15:27 UTC, kpicaza requested changes
thanks again, check that you commit a backup of the composer.json file,  you can delete it and we will merge the PR.

2021-10-21 16:55 UTC, AndreyPootMay commented
right, I check it

El jue, 21 oct 2021 a las 10:31, Koldo Picaza ***@***.***>)
escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In composer.json.save
> <https://github.com/pheature-flags/toggle-crud/pull/14#discussion_r733796851>
> :
>
> > @@ -0,0 +1,68 @@
> +{
>
> This file is not need ;-D
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pheature-flags/toggle-crud/pull/14#pullrequestreview-785863144>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG4PHKBVAWH63A5LMQAMGFTUIAW5JANCNFSM5GKWLIEQ>
> .
>

2021-11-20 12:45 UTC, closed without merging